### ISSUE TITLE
Manage multiple matrix domains

### ISSUE THREAD

**Issue by JimboJoe** [Josue-T/synapse_ynh#1]
Hi,

Is it possible to configure synapse to manage several matrix domains?

For example: I have a matrix.domain1.com synapse server, and I want to manage users @user:domain1.com, but also @user:domain2.com

Thanks!

**Comment by Josue-T** [comment]
For now it's not possible but I could see to make this app for multiple instance maybe.
Are you interested to use this app with multiple domain ?

**Comment by JimboJoe** [comment]
Yes, that would be interesting. My use case is that I host several domains that match the last names of my users.
But I'm a bit afraid running multiple synapse instances for this would be a bit heavy and overkill... 🙂

**Comment by Josue-T** [comment]
I see an other solution witch is to use the DNS.
Mybe you could use the SRV entry in your DNS for that. In this doc : https://github.com/matrix-org/synapse#setting-up-federation it's explained witch registry you can make for that.
The problem might be about LDAP because the user is probably linked automatically to the synapse domain.

**Comment by JimboJoe** [comment]
I think the biggest problem is [this](https://github.com/Josue-T/synapse_ynh/blob/master/conf/homeserver.yaml#L20). Installing on a subdomain.domain.com, I had to change that line prior to logging in the first user to have addresses as @user:domain.com (instead of @user:subdomain.domain.com), because synapse can't change the managed domain once users are created... So maybe it's limited to only one domain at the moment...?

**Comment by Josue-T** [comment]
No, if I understand the matrix doc you can have multiple domain attached to the same homeserver.
For example : 
you have your home server the address : synapse.domain1.tld
User 1 have the address : user1:domain2.tld
user2 : user2:domain3.tld
user4 : user3.domain4.tld
..

In that case you need to make a srv register witch look like that : 
_matrix._tcp.domain2.tld. 3600    IN      SRV     10 0 8448 synapse.domain1.tld.
_matrix._tcp.domain3.tld. 3600    IN      SRV     10 0 8448 synapse.domain1.tld.
_matrix._tcp.domain4.tld. 3600    IN      SRV     10 0 8448 synapse.domain1.tld.

While you install the homeserver in this case you set domain1.tld as the domain.
When your user will try to connect to your server the homeserver address will be domain1.tld

**Comment by Josue-T** [comment]
Hello,

I have made some test and my conclusion is that synapse can only run with only one domain. Si the only solution for now is to change the app for multi instance. So are you interested on that. I could do this if you need it.

**Comment by JimboJoe** [comment]
Well, provided synapse is a bit of a memory hog, I guess can't afford personally to host several instances for a need of only a couple of accounts, so please don't do that just for me 😉 
On another hand, as a potential future YunoHost official app, and maybe for a CHATONS usage, multi-instance support could prove useful :-)

**Comment by Josue-T** [comment]
Ok,

I'm also waiting on [dendrite](https://github.com/matrix-org/dendrite) wich will be more efficient and flexible. So I don't know how long synapse will be used.

**Comment by Josue-T** [comment]
Hello,

I have made a multi-instance version. It available here :
https://github.com/YunoHost-Apps/synapse_ynh/tree/testing
