### ISSUE TITLE
[Critical Security Fix] Update to 0.33.3.1

### ISSUE THREAD

**Issue by lapineige** [Josue-T/synapse_ynh#2]
https://matrix.org/blog/2018/09/05/pre-disclosure-upcoming-critical-security-fix-for-synapse/

**Comment by Josue-T** [comment]
YES, I have written this in my calendar :smile:

**Comment by Josue-T** [comment]
For information, the official place for the issue is here : https://github.com/YunoHost-Apps/synapse_ynh/issues

**Comment by lapineige** [comment]
Sorry my bad I didn't notice I wasn't on the official repo ^^
